simple_humanoid:
  ros__parameters:
    # Planner and Controller Configuration
    bt_navigator:
      ros__parameters:
        use_sim_time: True
        global_frame: map
        robot_base_frame: base_link
        odom_topic: /odom
        bt_loop_duration: 10
        default_server_timeout: 20
        enable_groot_monitoring: True
        groot_zmq_publisher_port: 1666
        groot_zmq_server_port: 1667
        default_nav_through_poses_bt_xml: "navigate_w_replanning_and_recovery.xml"
        default_nav_to_pose_bt_xml: "navigate_w_replanning_and_recovery.xml"
        plugin_lib_names:
          - nav2_compute_path_to_pose_action_bt_node
          - nav2_compute_path_through_poses_action_bt_node
          - nav2_smooth_path_action_bt_node
          - nav2_follow_path_action_bt_node
          - nav2_spin_action_bt_node
          - nav2_wait_action_bt_node
          - nav2_back_up_action_bt_node
          - nav2_drive_on_heading_bt_node
          - nav2_clear_costmap_service_bt_node
          - nav2_is_stuck_condition_bt_node
          - nav2_goal_reached_condition_bt_node
          - nav2_goal_updated_condition_bt_node
          - nav2_globally_updated_goal_condition_bt_node
          - nav2_is_path_valid_condition_bt_node
          - nav2_initial_pose_received_condition_bt_node
          - nav2_reinitialize_global_localization_service_bt_node
          - nav2_rate_controller_bt_node
          - nav2_distance_controller_bt_node
          - nav2_speed_controller_bt_node
          - nav2_truncate_path_action_bt_node
          - nav2_truncate_path_local_action_bt_node
          - nav2_goal_updater_node_bt_node
          - nav2_recovery_node_bt_node
          - nav2_pipeline_sequence_bt_node
          - nav2_round_robin_node_bt_node
          - nav2_transform_available_condition_bt_node
          - nav2_time_expired_condition_bt_node
          - nav2_path_expiring_timer_condition
          - nav2_distance_traveled_condition_bt_node
          - nav2_single_trigger_bt_node
          - nav2_is_battery_low_condition_bt_node
          - nav2_navigate_through_poses_action_bt_node
          - nav2_navigate_to_pose_action_bt_node
          - nav2_remove_passed_goals_action_bt_node
          - nav2_planner_selector_bt_node
          - nav2_controller_selector_bt_node
          - nav2_goal_checker_selector_bt_node
          - nav2_controller_cancel_bt_node
          - nav2_path_publisher_bt_node
          - nav2_velocity_smoother_bt_node

    # Behavior Tree Configuration
    behavior_server:
      ros__parameters:
        use_sim_time: True
        global_frame: map
        robot_base_frame: base_link
        odom_topic: /odom
        cycle_frequency: 10.0
        behavior_plugins: ["spin", "backup", "drive_on_heading", "wait"]
        spin.ros__parameters:
          spin_dist: 1.57
          time_allowance: 10
        backup.ros__parameters:
          backup_dist: -0.15
          backup_speed: 0.05
          time_allowance: 10
        drive_on_heading.ros__parameters:
          drive_on_heading_dist: 0.5
          drive_on_heading_angle_toler: 0.5
          time_allowance: 10
        wait.ros__parameters:
          time_wait: 5

    # Local Planner Configuration (For bipedal locomotion)
    local_costmap:
      ros__parameters:
        update_frequency: 5.0
        publish_frequency: 2.0
        global_frame: odom
        robot_base_frame: base_link
        use_sim_time: True
        rolling_window: true
        width: 6
        height: 6
        resolution: 0.05
        robot_radius: 0.3  # Adjusted for humanoid robot size
        plugins: ["voxel_layer", "inflation_layer"]
        inflation_layer:
          plugin: "nav2_costmap_2d::InflationLayer"
          cost_scaling_factor: 3.0
          inflation_radius: 0.55
        voxel_layer:
          plugin: "nav2_costmap_2d::VoxelLayer"
          enabled: True
          publish_voxel_map: False
          origin_z: 0.0
          z_resolution: 0.2
          z_voxels: 8
          max_obstacle_height: 2.0
          mark_threshold: 0
          observation_sources: scan
          scan:
            topic: /scan
            max_obstacle_height: 2.0
            clearing: True
            marking: True
            data_type: "LaserScan"
            raytrace_max_range: 3.0
            raytrace_min_range: 0.0
            obstacle_max_range: 2.5
            obstacle_min_range: 0.0

    # Global Planner Configuration
    global_costmap:
      ros__parameters:
        update_frequency: 1.0
        publish_frequency: 1.0
        global_frame: map
        robot_base_frame: base_link
        use_sim_time: True
        robot_radius: 0.3  # Adjusted for humanoid robot size
        resolution: 0.05
        plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
        obstacle_layer:
          plugin: "nav2_costmap_2d::ObstacleLayer"
          enabled: True
          observation_sources: scan
          scan:
            topic: /scan
            max_obstacle_height: 2.0
            clearing: True
            marking: True
            data_type: "LaserScan"
            raytrace_max_range: 3.0
            raytrace_min_range: 0.0
            obstacle_max_range: 2.5
            obstacle_min_range: 0.0
        static_layer:
          plugin: "nav2_costmap_2d::StaticLayer"
          map_subscribe_transient_local: True
        inflation_layer:
          plugin: "nav2_costmap_2d::InflationLayer"
          cost_scaling_factor: 3.0
          inflation_radius: 0.55

    # Controller Configuration for bipedal locomotion
    controller_server:
      ros__parameters:
        use_sim_time: True
        controller_frequency: 20.0
        min_x_velocity_threshold: 0.001
        min_y_velocity_threshold: 0.001
        min_theta_velocity_threshold: 0.001
        progress_checker_plugin: "progress_checker"
        goal_checker_plugin: "goal_checker"
        controller_plugins: ["FollowPath"]
        progress_checker:
          plugin: "nav2_controller::SimpleProgressChecker"
          required_movement_radius: 0.5
          movement_time_allowance: 10.0
        goal_checker:
          plugin: "nav2_controller::SimpleGoalChecker"
          xy_goal_tolerance: 0.25  # Increased for humanoid stability
          yaw_goal_tolerance: 0.25  # Increased for humanoid stability
          stateful: True
        FollowPath:
          plugin: "nav2_rotation_shim_controller::RotationShimController"
          angular_dist_threshold: 0.785
          forward_sampling_distance: 0.5
          rotate_to_heading_angular_vel: 1.0
          max_angular_accel: 3.2
          goal_angle_tolerance: 0.05
          use_rotate_to_heading: false
          rotate_to_heading_angular_vel: 1.0
          max_angular_accel: 3.2
          min_speed_xy: 0.0
          max_speed_xy: 0.5  # Slower for humanoid stability
          min_speed_theta: 0.0
          max_speed_theta: 1.0
          speed_limit_scale: 0.25
          xy_goal_tolerance: 0.25
          trans_stopped_velocity: 0.01
          short_circuit_initial_rotation: true
          primary_controller: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
          regulated_pure_pursuit:
            plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
            max_speed: 0.5  # Slower for humanoid stability
            min_speed: 0.1
            lookahead_dist: 0.6
            min_lookahead_dist: 0.3
            max_lookahead_dist: 0.9
            lookahead_time: 1.5
            rotate_to_heading_angular_vel: 1.0
            max_angular_accel: 3.2
            goal_dist_tol: 0.25
            linear_interp_step: 0.5
            transform_tolerance: 0.1
            use_velocity_scaled_lookahead_dist: false
            min_approach_linear_velocity: 0.05
            use_approach_linear_velocity_scaling: true
            approach_velocity_scaling_dist: 0.5
            use_regulated_linear_velocity_scaling: true
            use_cost_regulated_linear_velocity_scaling: true
            cost_scaling_dist: 0.6
            cost_scaling_gain: 1.0
            inflation_cost_scaling_factor: 3.0
            replan_frequency: 0.0
            use_dwa: false
            use_local_planer_limits: true
            max_linear_acceleration: 2.5
            max_linear_deceleration: -2.5
            debug_visualizations: false
            interpolate_path_to_resolution: false
            path_resolution: 0.003
            min_computed_path_resolution: 0.003